config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :games

  root 'venues#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :home_team, :class_name => "Team"
  belongs_to :away_team, :class_name => "Team"
  
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :home_one, :class_name => "Game", :foreign_key => 'home_team_id'
  has_many :away_one, :class_name => "Game", :foreign_key => 'away_team_id'
  
  def to_s
    name
  end
end

app/models/venue.rb
class Venue < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games=Game.all
  end

  def show
    @game=Game.find_by_id(params[:id])
  end

  def edit
    @game=Game.find_by_id(params[:id])
  end

  def new
    @game=Game.new
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:locality)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
	<div>
		<%= f.label :when %>
		<%= f.text_field :when %>
	</div>
	<div>
		<%= f.label :away_team_id %>
		<%= f.collection_select(:away_team_id, Team.all, :id, :name, prompt: true) %>
	</div>
	<div>
		<%= f.label :home_team_id %>
		<%= f.collection_select(:home_team_id, Team.all, :id, :to_s, prompt: true) %>
	</div>
	<div>
		<%= f.submit @game.new_record? ? "Create" : "Update"  %>
	</div>
<% end %>

app/views/games/edit.html.erb
<h1>Edit a game</h1>
<%= render 'form'%>

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

app/views/games/new.html.erb
<h1>New game</h1>
<%= render 'form'%>

app/views/games/show.html.erb
<h1>Game</h1>
<p>
  <strong>When:</strong>
  <%= @game.when.strftime("%d %b %Y") %>
</p>
<p>
  <strong>away team:</strong>
  <%= @game.away_team %>
</p>
<p>
  <strong>Home team:</strong>
  <%= @game.home_team %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestGames2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/venues/_form.html.erb
<%= form_for(@venue) do |f| %>
  <% if @venue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h2>

      <ul>
      <% @venue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :locality %><br>
    <%= f.text_field :locality %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing venue</h1>

<%= render 'form' %>

<%= link_to 'Show', @venue %> |
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<h1>Listing venues</h1>

<table>
  <thead>
    <tr>
      <th>Locality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @venues.each do |venue| %>
      <tr>
        <td><%= venue.locality %></td>
        <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Venue', new_venue_path %>

app/views/venues/new.html.erb
<h1>New venue</h1>

<%= render 'form' %>

<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Locality:</strong>
  <%= @venue.locality %>
</p>

<%= link_to 'Edit', edit_venue_path(@venue) %> |
<%= link_to 'Back', venues_path %>